/** Nationality / country → ISO 3166-1 alpha-2 for flag rendering (flagcdn). */

const NATIONALITY_TO_ISO: Record<string, string> = {
  American: "us",
  Argentine: "ar",
  Argentinian: "ar",
  Australian: "au",
  Austrian: "at",
  Belgian: "be",
  Brazilian: "br",
  British: "gb",
  Canadian: "ca",
  Chilean: "cl",
  Chinese: "cn",
  Colombian: "co",
  Czech: "cz",
  Danish: "dk",
  Dutch: "nl",
  Finnish: "fi",
  French: "fr",
  German: "de",
  Hungarian: "hu",
  Indian: "in",
  Indonesian: "id",
  Irish: "ie",
  Italian: "it",
  Japanese: "jp",
  Liechtensteiner: "li",
  Malaysian: "my",
  Mexican: "mx",
  Monegasque: "mc",
  "New Zealander": "nz",
  Polish: "pl",
  Portuguese: "pt",
  Rhodesian: "zw",
  Russian: "ru",
  "South African": "za",
  Spanish: "es",
  Swedish: "se",
  Swiss: "ch",
  Thai: "th",
  Uruguayan: "uy",
  Venezuelan: "ve",
};

const COUNTRY_TO_ISO: Record<string, string> = {
  Abu_Dhabi: "ae",
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Azerbaijan: "az",
  Bahrain: "bh",
  Belgium: "be",
  Brazil: "br",
  Canada: "ca",
  China: "cn",
  France: "fr",
  Germany: "de",
  Hungary: "hu",
  India: "in",
  Italy: "it",
  Japan: "jp",
  Korea: "kr",
  Malaysia: "my",
  Mexico: "mx",
  Monaco: "mc",
  Morocco: "ma",
  Netherlands: "nl",
  Portugal: "pt",
  Qatar: "qa",
  Russia: "ru",
  "Saudi Arabia": "sa",
  Singapore: "sg",
  "South Africa": "za",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Turkey: "tr",
  UAE: "ae",
  UK: "gb",
  "United Arab Emirates": "ae",
  "United Kingdom": "gb",
  "United States": "us",
  USA: "us",
  Vietnam: "vn",
};

export function nationalityToIso(nationality: string): string | null {
  return NATIONALITY_TO_ISO[nationality] ?? null;
}

export function countryToIso(country: string): string | null {
  return COUNTRY_TO_ISO[country] ?? null;
}
