/**
 * Editorial circuit guides for the current calendar, keyed by Jolpica
 * circuitId. Historical circuits without a guide render API-only pages.
 */
export type CornerNote = { corner: number | string; name?: string; note: string };

export type CircuitGuide = {
  circuitId: string;
  lengthKm: number;
  laps: number;
  corners: number;
  drsZoneCount: number;
  lapRecord: { time: string; driver: string; year: number } | null;
  elevationNote: string;
  overtakingSpots: string[];
  cornerGuide: CornerNote[];
  strategyNotes: string[];
  tireStress: "low" | "medium" | "high";
  funFacts: string[];
};

export const CURRENT_CIRCUIT_IDS = [
  "albert_park",
  "shanghai",
  "suzuka",
  "miami",
  "villeneuve",
  "monaco",
  "catalunya",
  "red_bull_ring",
  "silverstone",
  "spa",
  "hungaroring",
  "zandvoort",
  "monza",
  "madring",
  "baku",
  "marina_bay",
  "americas",
  "rodriguez",
  "interlagos",
  "vegas",
  "losail",
  "yas_marina",
] as const;

export const CIRCUIT_GUIDES: Record<string, CircuitGuide> = {
  albert_park: {
    circuitId: "albert_park",
    lengthKm: 5.278,
    laps: 58,
    corners: 14,
    drsZoneCount: 4,
    lapRecord: { time: "1:19.813", driver: "Charles Leclerc", year: 2024 },
    elevationNote: "Essentially flat — a parkland circuit around Albert Park Lake.",
    overtakingSpots: ["Turn 1 (after the pit straight)", "Turn 3", "Turn 11 after the fast middle sector"],
    cornerGuide: [
      { corner: 1, note: "Medium-speed right, heavy braking from the DRS run; classic lap-one squeeze." },
      { corner: 3, note: "Second big stop; late brakers dive down the inside." },
      { corner: "9-10", name: "Lakeside", note: "Flat-out sweep past the lake — one of the fastest sections on street-adjacent tracks." },
      { corner: 11, note: "High-speed right where the 2022 layout removed a chicane; big commitment." },
      { corner: 14, note: "Final right onto the pit straight; traction decides the DRS run." },
    ],
    strategyNotes: [
      "Four DRS zones make overtaking easier than the old layout — one-stop is standard.",
      "Safety cars are frequent early; teams keep an offset tire in reserve.",
    ],
    tireStress: "medium",
    funFacts: [
      "The track is made of public park roads reassembled every year.",
      "Australia hosted the season opener for most seasons since 1996.",
    ],
  },
  shanghai: {
    circuitId: "shanghai",
    lengthKm: 5.451,
    laps: 56,
    corners: 16,
    drsZoneCount: 2,
    lapRecord: { time: "1:32.238", driver: "Michael Schumacher", year: 2004 },
    elevationNote: "Mostly flat with subtle crests; built on reclaimed swampland atop polystyrene supports.",
    overtakingSpots: ["Turn 14 hairpin after the 1.2 km back straight", "Turn 1-2 snail complex"],
    cornerGuide: [
      { corner: "1-2", name: "The Snail", note: "Ever-tightening right that winds uphill then drops — mimics the Chinese character 'shang'." },
      { corner: 6, note: "Quick right where front-left graining begins." },
      { corner: "7-8", note: "Fast esses; commitment here sets up the middle sector." },
      { corner: 13, note: "Long right onto the back straight — traction and battery deployment critical." },
      { corner: 14, note: "The overtaking hairpin at the end of F1's longest straights." },
    ],
    strategyNotes: [
      "Front-left graining historically dictates stint length.",
      "The long back straight rewards low-drag setups despite the twisty first sector.",
    ],
    tireStress: "high",
    funFacts: [
      "The circuit layout is based on the Chinese character 上 (shang).",
      "Schumacher's 2004 lap record is among the oldest still standing.",
    ],
  },
  suzuka: {
    circuitId: "suzuka",
    lengthKm: 5.807,
    laps: 53,
    corners: 18,
    drsZoneCount: 2,
    lapRecord: { time: "1:30.983", driver: "Lewis Hamilton", year: 2019 },
    elevationNote: "Rolling elevation throughout; the crossover bridge makes it F1's only figure-eight.",
    overtakingSpots: ["Turn 1 entry", "The chicane (Casio Triangle)", "130R exit into the chicane"],
    cornerGuide: [
      { corner: "3-7", name: "The Esses", note: "Legendary uphill snake — rhythm is everything, one error ruins five corners." },
      { corner: 8, name: "Degner 1", note: "Fast right with zero runway; punishes greed instantly." },
      { corner: 11, name: "Hairpin", note: "Slowest point; rare passing chance with a good exit from Degner." },
      { corner: "15", name: "130R", note: "Once the most fearsome corner in F1 — now flat, still spectacular." },
      { corner: "16-17", name: "Casio Triangle", note: "Final chicane; the classic last-lap lunge spot." },
    ],
    strategyNotes: [
      "High-energy corners stress every tire; two stops are common.",
      "Track position matters — the esses make following painful.",
    ],
    tireStress: "high",
    funFacts: [
      "Suzuka is the only figure-eight circuit on the calendar.",
      "Built in 1962 as a Honda test track, designed by John Hugenholtz.",
      "Thirteen world championships have been decided here.",
    ],
  },
  miami: {
    circuitId: "miami",
    lengthKm: 5.412,
    laps: 57,
    corners: 19,
    drsZoneCount: 3,
    lapRecord: { time: "1:29.708", driver: "Max Verstappen", year: 2023 },
    elevationNote: "Mostly flat with an artificial hill through Turns 13–16 under the turnpike ramps.",
    overtakingSpots: ["Turn 1", "Turn 11 after the long back straight", "Turn 17"],
    cornerGuide: [
      { corner: 1, note: "Wide entry invites three-abreast lap-one chaos." },
      { corner: "4-8", note: "Long left-hand sweep around the stadium — flat but dirty off-line." },
      { corner: 11, note: "Main overtaking spot after the longest full-throttle run." },
      { corner: "14-15", note: "Awkward slow chicane under the highway; bumps and low grip." },
      { corner: 17, note: "Heavy stop before the final two corners; late-race lunges happen here." },
    ],
    strategyNotes: [
      "Track surface evolves massively across the weekend.",
      "Off-line grip is poor, making defense easier than the layout suggests.",
    ],
    tireStress: "medium",
    funFacts: [
      "The circuit loops around Hard Rock Stadium, home of the Miami Dolphins.",
      "The 'marina' in early editions featured boats parked on painted asphalt.",
    ],
  },
  villeneuve: {
    circuitId: "villeneuve",
    lengthKm: 4.361,
    laps: 70,
    corners: 14,
    drsZoneCount: 3,
    lapRecord: { time: "1:13.078", driver: "Valtteri Bottas", year: 2019 },
    elevationNote: "Flat — built on the man-made Île Notre-Dame in the St. Lawrence River.",
    overtakingSpots: ["Turn 10 hairpin", "Final chicane after the Casino straight", "Turn 1"],
    cornerGuide: [
      { corner: "1-2", note: "Awkward left-right where lap-one accidents are tradition." },
      { corner: "6-7", note: "Quick chicane between walls; kerb riding decides lap time." },
      { corner: 10, name: "L'Épingle", note: "The hairpin — prime overtaking, prime lock-ups." },
      { corner: "13-14", name: "Wall of Champions", note: "Final chicane whose exit wall has collected Hill, Villeneuve and Schumacher." },
    ],
    strategyNotes: [
      "Top speed and braking stability trump downforce here.",
      "Safety car probability is among the highest of the season — strategy stays flexible.",
    ],
    tireStress: "low",
    funFacts: [
      "Named for Gilles Villeneuve, who won the first race here in 1978.",
      "The 'Wall of Champions' earned its name in 1999 by claiming three world champions.",
      "Groundhogs are regular (and occasionally race-affecting) trackside visitors.",
    ],
  },
  monaco: {
    circuitId: "monaco",
    lengthKm: 3.337,
    laps: 78,
    corners: 19,
    drsZoneCount: 1,
    lapRecord: { time: "1:12.909", driver: "Lewis Hamilton", year: 2021 },
    elevationNote: "Dramatic — climbs from the harbor to Casino Square then plunges to the sea.",
    overtakingSpots: ["Into the Nouvelle Chicane (rare)", "Sainte Dévote on lap one"],
    cornerGuide: [
      { corner: 1, name: "Sainte Dévote", note: "Uphill right; the funnel where first laps go wrong." },
      { corner: "3-4", name: "Casino", note: "Blind crest past the Casino — millimeters from the barriers." },
      { corner: 6, name: "Grand Hotel Hairpin", note: "The slowest corner in F1 (~45 km/h); full steering lock." },
      { corner: "10-11", name: "Nouvelle Chicane", note: "Harborside chicane; the only real overtaking chance." },
      { corner: "13-14", name: "Piscine", note: "The swimming pool esses — total commitment between walls." },
      { corner: 18, name: "Rascasse", note: "Tight right where Schumacher famously 'parked' in 2006 qualifying." },
    ],
    strategyNotes: [
      "Qualifying is everything; the race is often decided Saturday.",
      "Overcut and undercut both work because track position dwarfs pace.",
    ],
    tireStress: "low",
    funFacts: [
      "Monaco has run largely unchanged since 1929.",
      "Graham Hill and Ayrton Senna define the 'King of Monaco' myth — Senna won six.",
      "The race distance is F1's shortest because average speed is so low.",
    ],
  },
  catalunya: {
    circuitId: "catalunya",
    lengthKm: 4.657,
    laps: 66,
    corners: 14,
    drsZoneCount: 2,
    lapRecord: { time: "1:16.330", driver: "Max Verstappen", year: 2023 },
    elevationNote: "Gentle rises through the stadium section; long flowing gradients elsewhere.",
    overtakingSpots: ["Turn 1 after the main straight", "Turn 10"],
    cornerGuide: [
      { corner: 1, note: "Main overtaking zone; wide entry, multiple lines." },
      { corner: 3, note: "Long right that eats front-left tires — the classic car-balance test." },
      { corner: 9, name: "Campsa", note: "Blind, fast right over a crest; total aero confidence needed." },
      { corner: "10", name: "La Caixa", note: "Downhill left hairpin; the second DRS pass point." },
      { corner: "13-14", note: "Fast final corners since the chicane's removal — critical for the DRS run." },
    ],
    strategyNotes: [
      "Teams test here — everyone knows the track, so margins are tiny.",
      "High front-left wear historically pushes two-stop races.",
    ],
    tireStress: "high",
    funFacts: [
      "For decades the reference track for car development correlation.",
      "Turn 3 flat-or-not was the annual measure of a car's downforce.",
    ],
  },
  red_bull_ring: {
    circuitId: "red_bull_ring",
    lengthKm: 4.318,
    laps: 71,
    corners: 10,
    drsZoneCount: 3,
    lapRecord: { time: "1:05.619", driver: "Carlos Sainz", year: 2020 },
    elevationNote: "Steep Styrian hillside — 65 m of climb, with uphill braking zones.",
    overtakingSpots: ["Turn 3", "Turn 4", "Turn 1 with a good exit from the final corners"],
    cornerGuide: [
      { corner: 1, note: "Short uphill right; track-limits penalties lurk on exit." },
      { corner: 3, note: "Steep uphill hairpin at the end of the longest climb — pass or be passed." },
      { corner: 4, note: "Downhill entry, another DRS-assisted braking duel." },
      { corner: "6-7", note: "Fast downhill left-left; rhythm section with gravel waiting." },
      { corner: "9-10", note: "Final two rights; exit speed sets up the whole lap." },
    ],
    strategyNotes: [
      "F1's shortest lap time — traffic in qualifying is chronic.",
      "Three DRS zones in ten corners produce constant overtaking.",
    ],
    tireStress: "medium",
    funFacts: [
      "The original Österreichring was nearly twice as long and terrifyingly fast.",
      "A bull sculpture watches over Turn 6 from the hillside.",
    ],
  },
  silverstone: {
    circuitId: "silverstone",
    lengthKm: 5.891,
    laps: 52,
    corners: 18,
    drsZoneCount: 2,
    lapRecord: { time: "1:27.097", driver: "Max Verstappen", year: 2020 },
    elevationNote: "Gentle airfield undulations; wind direction changes the car more than gradient.",
    overtakingSpots: ["Stowe", "Turn 3 (Village)", "Copse with DRS bravery", "Brooklands"],
    cornerGuide: [
      { corner: 9, name: "Copse", note: "Near-flat right at 290 km/h; scene of the 2021 Hamilton–Verstappen collision." },
      { corner: "10-14", name: "Maggotts-Becketts-Chapel", note: "The best sequence of corners in F1 — direction changes at 250+ km/h." },
      { corner: 15, name: "Stowe", note: "Fast right at the end of Hangar Straight; classic overtaking." },
      { corner: "16-17", name: "Vale", note: "Heavy braking chicane — lunge spot and exit-compromise trap." },
      { corner: 18, name: "Club", note: "Long final right onto the pit straight." },
    ],
    strategyNotes: [
      "Front-left suffers through the fast sweeps; blistering is a threat.",
      "Wind shifts between sessions upset qualifying setups more than most venues.",
    ],
    tireStress: "high",
    funFacts: [
      "Hosted the first world championship Grand Prix on 13 May 1950.",
      "A WWII Wellington bomber base — the three runways still shape the layout.",
    ],
  },
  spa: {
    circuitId: "spa",
    lengthKm: 7.004,
    laps: 44,
    corners: 19,
    drsZoneCount: 2,
    lapRecord: { time: "1:46.286", driver: "Valtteri Bottas", year: 2018 },
    elevationNote: "The Ardennes rollercoaster — over 100 m of elevation, with Eau Rouge climbing 40 m.",
    overtakingSpots: ["Les Combes after the Kemmel Straight", "Bus Stop chicane", "La Source exit runs"],
    cornerGuide: [
      { corner: 1, name: "La Source", note: "Hairpin immediately after the start; lap-one concertina." },
      { corner: "3-4", name: "Eau Rouge / Raidillon", note: "The most famous corner complex in racing — a blind, compressing 40 m climb." },
      { corner: 7, name: "Les Combes", note: "End of the Kemmel Straight; the primary DRS overtaking zone." },
      { corner: 10, name: "Pouhon", note: "Double-apex downhill left, taken near-flat by the brave." },
      { corner: "13-14", name: "Stavelot", note: "Long loaded rights leading to the flat-out blast home." },
      { corner: "18-19", name: "Bus Stop", note: "Final chicane; last-lap dives are a Spa tradition." },
    ],
    strategyNotes: [
      "Weather can differ across the 7 km lap — rain at one end, dry at the other.",
      "Low-drag setups win the Kemmel drag race but suffer in sector two.",
    ],
    tireStress: "high",
    funFacts: [
      "Spa is the longest circuit on the calendar at 7.004 km.",
      "The original 1920s layout used public roads and measured over 14 km.",
      "Its microclimate makes 'Spa weather' a strategy term of art.",
    ],
  },
  hungaroring: {
    circuitId: "hungaroring",
    lengthKm: 4.381,
    laps: 70,
    corners: 14,
    drsZoneCount: 1,
    lapRecord: { time: "1:16.627", driver: "Lewis Hamilton", year: 2020 },
    elevationNote: "Sits in a natural amphitheater valley; constant small gradients.",
    overtakingSpots: ["Turn 1 (the only realistic spot)", "Turn 2 as a crossover"],
    cornerGuide: [
      { corner: 1, note: "Downhill braking, wide entry — virtually all passes happen here." },
      { corner: 2, note: "Downhill left; the counter-attack corner for cars passed into 1." },
      { corner: 4, note: "Fast blind left over a crest — the lap's biggest commitment." },
      { corner: "6-7", note: "Chicane where kerb usage makes or breaks the middle sector." },
      { corner: 14, note: "Long final right; exit sets up the only DRS zone." },
    ],
    strategyNotes: [
      "Often called 'Monaco without walls' — track position is king.",
      "High summer heat makes tire management decisive despite low speeds.",
    ],
    tireStress: "medium",
    funFacts: [
      "First Grand Prix behind the Iron Curtain (1986).",
      "Nelson Piquet's cross-armed opposite-lock pass on Senna in 1986 is circuit legend.",
    ],
  },
  zandvoort: {
    circuitId: "zandvoort",
    lengthKm: 4.259,
    laps: 72,
    corners: 14,
    drsZoneCount: 2,
    lapRecord: { time: "1:11.097", driver: "Lewis Hamilton", year: 2021 },
    elevationNote: "Sand-dune terrain with two steeply banked corners (Turns 3 and 14).",
    overtakingSpots: ["Turn 1 (Tarzan)", "Turn 11 after the back section"],
    cornerGuide: [
      { corner: 1, name: "Tarzan", note: "Banked hairpin with multiple lines — the great overtaking equalizer." },
      { corner: 3, name: "Hugenholtz", note: "18° banked left; cars run shoulder-to-shoulder at different heights." },
      { corner: 7, name: "Scheivlak", note: "Blind, fast right plunging between the dunes." },
      { corner: "13-14", name: "Arie Luyendyk", note: "Banked final corner taken flat with DRS open — unique in F1." },
    ],
    strategyNotes: [
      "The banking lets DRS open through the final corner, extending the main straight.",
      "Narrow and winding — undercuts beat on-track passing.",
    ],
    tireStress: "medium",
    funFacts: [
      "The 'Dutch orange army' turns the dunes into a festival for Verstappen.",
      "Zandvoort returned in 2021 after a 36-year absence.",
    ],
  },
  monza: {
    circuitId: "monza",
    lengthKm: 5.793,
    laps: 53,
    corners: 11,
    drsZoneCount: 2,
    lapRecord: { time: "1:21.046", driver: "Rubens Barrichello", year: 2004 },
    elevationNote: "Flat parkland; the abandoned banked oval still looms in the trees.",
    overtakingSpots: ["Turn 1 chicane", "Roggia chicane", "Ascari entry"],
    cornerGuide: [
      { corner: "1-2", name: "Variante del Rettifilo", note: "First chicane after a 340 km/h run — the season's biggest braking event." },
      { corner: "4-5", name: "Variante della Roggia", note: "Second chicane; kerb attack and lunges." },
      { corner: "6-7", name: "Lesmo 1 & 2", note: "Two quick rights whose exits feed the back straight." },
      { corner: "8-10", name: "Ascari", note: "Fast left-right-left; the lap's rhythm test." },
      { corner: 11, name: "Parabolica", note: "The long final right onto the main straight — carry speed or lose the tow battle." },
    ],
    strategyNotes: [
      "Skinny wings everywhere; slipstream 'trains' define qualifying.",
      "Brake cooling and chicane kerbs decide reliability.",
    ],
    tireStress: "low",
    funFacts: [
      "The 'Temple of Speed' has hosted F1 every year but one since 1950.",
      "The average lap speed exceeds 250 km/h — the fastest of the season.",
      "The tifosi's podium invasion under the Ferrari flag is an F1 ritual.",
    ],
  },
  madring: {
    circuitId: "madring",
    lengthKm: 5.47,
    laps: 57,
    corners: 22,
    drsZoneCount: 3,
    lapRecord: null,
    elevationNote: "Mixed street-and-permanent layout around Madrid's IFEMA district, with a steeply banked signature corner.",
    overtakingSpots: ["Turn 1", "The banked 'La Monumental' curve exit", "End of the long back section"],
    cornerGuide: [
      { corner: 1, note: "Heavy stop after the pit straight — the first passing zone on the new layout." },
      { corner: "10-12", note: "Tight infield sequence between the exhibition halls; track position matters." },
      { corner: "La Monumental", note: "The 24°-banked signature corner, the steepest banking in modern F1." },
      { corner: 22, note: "Final corner onto the main straight; traction is everything." },
    ],
    strategyNotes: [
      "A brand-new venue for 2026 — expect evolving grip and cautious first-year strategy.",
      "Hybrid street/permanent surface changes make tire warm-up tricky.",
    ],
    tireStress: "medium",
    funFacts: [
      "Madrid's Madring hosts the Spanish Grand Prix from 2026.",
      "Around 90% of spectators can arrive by public transport — a first for F1.",
    ],
  },
  baku: {
    circuitId: "baku",
    lengthKm: 6.003,
    laps: 51,
    corners: 20,
    drsZoneCount: 2,
    lapRecord: { time: "1:43.009", driver: "Charles Leclerc", year: 2019 },
    elevationNote: "Sea-level start/finish with a climb into the medieval old town section.",
    overtakingSpots: ["Turn 1 after the 2.2 km flat-out blast", "Turn 3"],
    cornerGuide: [
      { corner: 1, note: "The braking zone at the end of F1's longest full-throttle section (~2.2 km)." },
      { corner: "8-9", name: "Castle Section", note: "The track narrows to one car's width past the old city walls." },
      { corner: 15, note: "Downhill left where late-race gambles end in the runoff." },
      { corner: "16-20", note: "The endless flat-out run home — slipstream heaven." },
    ],
    strategyNotes: [
      "Chaos capital: safety cars and red flags regularly invert results.",
      "Low drag vs. castle-section grip is the eternal setup dilemma.",
    ],
    tireStress: "low",
    funFacts: [
      "The 2021 race saw Verstappen's tire fail while leading, then Hamilton locked up from P1 at the restart.",
      "Winds off the Caspian Sea can move braking points lap to lap.",
    ],
  },
  marina_bay: {
    circuitId: "marina_bay",
    lengthKm: 4.94,
    laps: 62,
    corners: 19,
    drsZoneCount: 3,
    lapRecord: { time: "1:34.486", driver: "Daniel Ricciardo", year: 2024 },
    elevationNote: "Flat harborfront streets — the challenge is heat and humidity, not gradient.",
    overtakingSpots: ["Turn 7", "Turn 14 after the DRS runs", "Turn 16 with a mistake ahead"],
    cornerGuide: [
      { corner: 1, note: "Tight left immediately testing cold brakes and nerves." },
      { corner: 7, note: "End of the longest straight — main overtaking chance." },
      { corner: "10", note: "Awkward left kink where walls have collected champions." },
      { corner: 14, note: "Heavy braking under the grandstands; second passing zone." },
      { corner: "16-19", note: "The final flowing section since the 2023 layout change removed the chicane." },
    ],
    strategyNotes: [
      "The most physical race of the year — two hours at 80% humidity.",
      "Safety car probability historically near 100%; strategy stays reactive.",
    ],
    tireStress: "medium",
    funFacts: [
      "F1's first night race (2008), run under 1,600 floodlights.",
      "Drivers lose up to 3 kg of sweat during the race.",
    ],
  },
  americas: {
    circuitId: "americas",
    lengthKm: 5.513,
    laps: 56,
    corners: 20,
    drsZoneCount: 2,
    lapRecord: { time: "1:36.169", driver: "Charles Leclerc", year: 2019 },
    elevationNote: "The Turn 1 hill climbs 40 m from the grid — the steepest start in F1.",
    overtakingSpots: ["Turn 1 crest", "Turn 12 after the back straight", "Turn 15"],
    cornerGuide: [
      { corner: 1, note: "Blind uphill left — wide entry fans four cars abreast on lap one." },
      { corner: "3-6", note: "Silverstone-inspired esses; flow and rhythm at 250 km/h." },
      { corner: 11, note: "Hairpin onto the 1 km back straight; exit is everything." },
      { corner: 12, note: "Main DRS overtaking zone into a wide braking area." },
      { corner: "16-18", note: "Triple-apex right modeled on Istanbul's Turn 8." },
    ],
    strategyNotes: [
      "Bumps from shifting Texas clay unsettle stiff cars.",
      "Two-stop races are common; tire degradation is real here.",
    ],
    tireStress: "high",
    funFacts: [
      "COTA's design remixes famous corners from Silverstone, Istanbul and Hockenheim.",
      "The 77 m observation tower overlooks the amphitheater esses.",
    ],
  },
  rodriguez: {
    circuitId: "rodriguez",
    lengthKm: 4.304,
    laps: 71,
    corners: 17,
    drsZoneCount: 3,
    lapRecord: { time: "1:17.774", driver: "Valtteri Bottas", year: 2021 },
    elevationNote: "At 2,285 m altitude — the thin air cuts downforce and engine cooling ~25%.",
    overtakingSpots: ["Turn 1 after the 1.2 km straight", "Turn 4", "Turn 6"],
    cornerGuide: [
      { corner: 1, note: "Massive braking from 350+ km/h — the highest top speeds of the year happen here." },
      { corner: "4-6", note: "The 'S' section; DRS-assisted attacks continue into these switchbacks." },
      { corner: "7-11", note: "Fast, flowing esses where thin air makes cars slide like it's wet." },
      { corner: "12-14", name: "Foro Sol", note: "The stadium section — 40,000 fans in a former baseball park." },
      { corner: 17, name: "Peraltada", note: "The half-remaining legendary banked final corner." },
    ],
    strategyNotes: [
      "Thin air = Monaco downforce with Monza straight-line speed.",
      "Cooling limits, not grip, often dictate how hard drivers can push.",
    ],
    tireStress: "medium",
    funFacts: [
      "Named for Mexico's racing brothers Ricardo and Pedro Rodríguez.",
      "The podium ceremony happens in the stadium section — F1's loudest.",
    ],
  },
  interlagos: {
    circuitId: "interlagos",
    lengthKm: 4.309,
    laps: 71,
    corners: 15,
    drsZoneCount: 2,
    lapRecord: { time: "1:10.540", driver: "Valtteri Bottas", year: 2018 },
    elevationNote: "Carved into a natural bowl; anti-clockwise with a punishing uphill finish.",
    overtakingSpots: ["Turn 1 (Senna S)", "Turn 4 (Descida do Lago)", "Turn 12 uphill"],
    cornerGuide: [
      { corner: "1-2", name: "Senna S", note: "Downhill left-right named for the hometown hero; the great overtaking spot." },
      { corner: 4, name: "Descida do Lago", note: "Fast downhill left onto the back straight; second DRS zone follows." },
      { corner: 8, name: "Laranjinha", note: "Slow infield left where mistakes compound onto the climb." },
      { corner: 12, name: "Juncao", note: "The corner that launches the endless uphill run to the line." },
    ],
    strategyNotes: [
      "Weather roulette — storms build over the bowl in minutes.",
      "Short lap and close pack make safety-car timing decisive.",
    ],
    tireStress: "medium",
    funFacts: [
      "Officially Autódromo José Carlos Pace, but everyone says Interlagos — 'between the lakes'.",
      "Title deciders: 2008's Hamilton-by-one-corner remains the most dramatic finish ever.",
      "One of only a handful of anti-clockwise circuits in F1.",
    ],
  },
  vegas: {
    circuitId: "vegas",
    lengthKm: 6.201,
    laps: 50,
    corners: 17,
    drsZoneCount: 2,
    lapRecord: { time: "1:34.876", driver: "Lando Norris", year: 2024 },
    elevationNote: "Pancake-flat down the Strip; the challenge is cold desert night temperatures.",
    overtakingSpots: ["Turn 14 at the end of the Strip", "Turn 1", "Turn 5"],
    cornerGuide: [
      { corner: 1, note: "Tight left after the start; cold tires meet concrete walls." },
      { corner: 5, note: "Heavy stop after the first long blast; early-lap passing." },
      { corner: "12", note: "The corner that releases cars onto the 1.9 km Strip straight past the Sphere." },
      { corner: 14, note: "The braking zone at the end of the Strip — the signature overtake spot." },
    ],
    strategyNotes: [
      "Track temperatures near 15°C make tire warm-up the defining problem.",
      "Long straights + low grip = huge slipstream battles and graining management.",
    ],
    tireStress: "low",
    funFacts: [
      "The race runs at night down the Las Vegas Strip past the Bellagio fountains.",
      "F1 first raced in Vegas in 1981–82 — in the Caesars Palace car park.",
    ],
  },
  losail: {
    circuitId: "losail",
    lengthKm: 5.419,
    laps: 57,
    corners: 16,
    drsZoneCount: 1,
    lapRecord: { time: "1:22.384", driver: "Lando Norris", year: 2024 },
    elevationNote: "Flat desert circuit ringed by floodlights — built for MotoGP, flowing by design.",
    overtakingSpots: ["Turn 1 after the 1 km main straight", "Turn 4"],
    cornerGuide: [
      { corner: 1, note: "Wide right at the end of the kilometre-long straight." },
      { corner: "5-6", note: "Committed medium-speed left-right where the lap builds rhythm." },
      { corner: "12-14", note: "Fast triple-right loading the front-left relentlessly." },
      { corner: 16, note: "Final corner onto the main straight; exit quality defines the DRS attack." },
    ],
    strategyNotes: [
      "Tire energy is extreme — the 2023 race mandated maximum 18-lap stints.",
      "Night-race heat plus high-speed corners make it among the most physical rounds.",
    ],
    tireStress: "high",
    funFacts: [
      "Built in under a year for MotoGP in 2004; F1 arrived in 2021.",
      "The 2023 race saw multiple drivers treated for heat exhaustion.",
    ],
  },
  yas_marina: {
    circuitId: "yas_marina",
    lengthKm: 5.281,
    laps: 58,
    corners: 16,
    drsZoneCount: 2,
    lapRecord: { time: "1:26.103", driver: "Max Verstappen", year: 2021 },
    elevationNote: "Flat marina layout; the race starts at dusk and finishes under floodlights.",
    overtakingSpots: ["Turn 6 hairpin", "Turn 9 after the second long straight"],
    cornerGuide: [
      { corner: "5-6", note: "Chicane-hairpin combination ending the first sector; main passing zone." },
      { corner: 9, note: "Hard stop after the longest straight — DRS lunges land here." },
      { corner: "12-13", note: "The hotel section — walls tighten as the lap winds beneath the W Abu Dhabi." },
      { corner: 16, note: "Final left through the hotel's light tunnel onto the pit straight." },
    ],
    strategyNotes: [
      "The 2021 reprofiling improved racing, but track position still dominates.",
      "Falling track temperatures through the twilight race shift balance rearward.",
    ],
    tireStress: "low",
    funFacts: [
      "The season finale since 2014 — and decider of the infamous 2021 championship.",
      "The pit exit tunnels beneath the track itself.",
    ],
  },
};

export function getCircuitGuide(circuitId: string): CircuitGuide | undefined {
  return CIRCUIT_GUIDES[circuitId];
}
