/**
 * Editorial metadata for Formula One constructors, keyed by Jolpica
 * constructorId. Merged with live API data at render time — any constructor
 * missing from this map must degrade gracefully to API-only display.
 */
export type TeamMeta = {
  constructorId: string;
  name: string;
  shortName: string;
  /** Primary accent color (hex). */
  color: string;
  secondaryColor: string;
  base: string;
  principal: string;
  powerUnit: string;
  firstEntry: number;
  championships: number;
  funFacts: string[];
  current: boolean;
};

export const TEAM_META: Record<string, TeamMeta> = {
  mclaren: {
    constructorId: "mclaren",
    name: "McLaren",
    shortName: "McLaren",
    color: "#FF8000",
    secondaryColor: "#47C7FC",
    base: "Woking, United Kingdom",
    principal: "Andrea Stella",
    powerUnit: "Mercedes",
    firstEntry: 1966,
    championships: 10,
    funFacts: [
      "Founded by New Zealand racer Bruce McLaren, who won his first Grand Prix aged 22.",
      "The McLaren Technology Centre in Woking features a lake used to cool the building's wind tunnel.",
      "McLaren's papaya orange harks back to the colors Bruce McLaren raced in the 1960s.",
      "In 1988 McLaren won 15 of 16 races — still one of the most dominant seasons ever.",
    ],
    current: true,
  },
  ferrari: {
    constructorId: "ferrari",
    name: "Ferrari",
    shortName: "Ferrari",
    color: "#E8002D",
    secondaryColor: "#FFF200",
    base: "Maranello, Italy",
    principal: "Frédéric Vasseur",
    powerUnit: "Ferrari",
    firstEntry: 1950,
    championships: 16,
    funFacts: [
      "Ferrari is the only team to have competed in every Formula One season since 1950.",
      "The famous prancing horse emblem was a gift from the family of WWI flying ace Francesco Baracca.",
      "Maranello's wind tunnel was designed by architect Renzo Piano.",
      "Ferrari's 16 constructors' titles are the most of any team in the sport's history.",
    ],
    current: true,
  },
  red_bull: {
    constructorId: "red_bull",
    name: "Red Bull Racing",
    shortName: "Red Bull",
    color: "#3671C6",
    secondaryColor: "#FDD900",
    base: "Milton Keynes, United Kingdom",
    principal: "Laurent Mekies",
    powerUnit: "Red Bull Ford",
    firstEntry: 2005,
    championships: 6,
    funFacts: [
      "Red Bull bought the Jaguar team for a symbolic $1 in 2004 — with a promise to invest $400m.",
      "Their 2023 season set the record for win percentage: 21 victories from 22 races.",
      "From 2026 Red Bull builds its own power units in partnership with Ford.",
      "Chief designer Adrian Newey's cars won titles for three different teams before he departed in 2024.",
    ],
    current: true,
  },
  mercedes: {
    constructorId: "mercedes",
    name: "Mercedes",
    shortName: "Mercedes",
    color: "#27F4D2",
    secondaryColor: "#565F64",
    base: "Brackley, United Kingdom",
    principal: "Toto Wolff",
    powerUnit: "Mercedes",
    firstEntry: 1954,
    championships: 8,
    funFacts: [
      "Mercedes won eight consecutive constructors' championships from 2014 to 2021 — a record.",
      "The team's Brackley factory started life as BAR, then Honda, then Brawn GP.",
      "Mercedes first raced in F1 in 1954 with Juan Manuel Fangio, winning the title immediately.",
      "The silver color dates to 1934, when Mercedes allegedly stripped white paint to save weight.",
    ],
    current: true,
  },
  aston_martin: {
    constructorId: "aston_martin",
    name: "Aston Martin",
    shortName: "Aston Martin",
    color: "#229971",
    secondaryColor: "#CEDC00",
    base: "Silverstone, United Kingdom",
    principal: "Andy Cowell",
    powerUnit: "Honda",
    firstEntry: 1959,
    championships: 0,
    funFacts: [
      "The modern team traces its lineage through Jordan, Midland, Spyker, Force India and Racing Point.",
      "Aston Martin's new Silverstone campus includes F1's newest wind tunnel.",
      "Legendary designer Adrian Newey joined as managing technical partner in 2025.",
      "From 2026 the team becomes Honda's factory works partner.",
    ],
    current: true,
  },
  alpine: {
    constructorId: "alpine",
    name: "Alpine",
    shortName: "Alpine",
    color: "#FF87BC",
    secondaryColor: "#2173B8",
    base: "Enstone, United Kingdom",
    principal: "Steve Nielsen",
    powerUnit: "Mercedes",
    firstEntry: 1977,
    championships: 2,
    funFacts: [
      "The Enstone team won world titles as Benetton (1995) and Renault (2005, 2006).",
      "Alpine is Renault's sports car brand, founded in Dieppe in 1955.",
      "From 2026 Alpine runs Mercedes customer power units, ending decades of Renault engines.",
      "Fernando Alonso won both of Enstone's drivers' championships in 2005 and 2006.",
    ],
    current: true,
  },
  williams: {
    constructorId: "williams",
    name: "Williams",
    shortName: "Williams",
    color: "#64C4FF",
    secondaryColor: "#00205B",
    base: "Grove, United Kingdom",
    principal: "James Vowles",
    powerUnit: "Mercedes",
    firstEntry: 1978,
    championships: 9,
    funFacts: [
      "Williams' nine constructors' titles are the third most in F1 history.",
      "Founder Sir Frank Williams led the team for 43 years — the longest tenure of any team boss.",
      "In 1992 the FW14B's active suspension made it one of the most technologically advanced F1 cars ever.",
      "Seven different drivers won world championships in Williams cars.",
    ],
    current: true,
  },
  rb: {
    constructorId: "rb",
    name: "Racing Bulls",
    shortName: "Racing Bulls",
    color: "#6692FF",
    secondaryColor: "#C8102E",
    base: "Faenza, Italy",
    principal: "Alan Permane",
    powerUnit: "Red Bull Ford",
    firstEntry: 1985,
    championships: 0,
    funFacts: [
      "The Faenza team began as Minardi, a beloved underdog that ran from 1985 to 2005.",
      "As Toro Rosso, it gave Sebastian Vettel his first win at Monza 2008 — before Red Bull Racing had won a race.",
      "The team has launched the careers of Vettel, Ricciardo, Verstappen, Sainz and many more.",
      "It is the only Italian-based team on the grid besides Ferrari.",
    ],
    current: true,
  },
  audi: {
    constructorId: "audi",
    name: "Audi",
    shortName: "Audi",
    color: "#00E701",
    secondaryColor: "#1A1A1A",
    base: "Hinwil, Switzerland",
    principal: "Jonathan Wheatley",
    powerUnit: "Audi",
    firstEntry: 2026,
    championships: 0,
    funFacts: [
      "Audi's F1 entry absorbed the Sauber team, which had raced from Hinwil since 1993.",
      "The power unit is built in Neuburg, Germany — Audi's first works F1 engine program.",
      "Sauber's greatest era was as BMW Sauber, nearly winning the 2008 title with Robert Kubica.",
      "Audi entered F1 attracted by the 2026 sustainable-fuel hybrid regulations.",
    ],
    current: true,
  },
  haas: {
    constructorId: "haas",
    name: "Haas F1 Team",
    shortName: "Haas",
    color: "#B6BABD",
    secondaryColor: "#E6002B",
    base: "Kannapolis, United States",
    principal: "Ayao Komatsu",
    powerUnit: "Ferrari",
    firstEntry: 2016,
    championships: 0,
    funFacts: [
      "Haas is the first American-owned F1 team since the 1980s.",
      "The team scored points on debut in Australia 2016 — a rarity for new teams.",
      "Haas operates from three sites: Kannapolis (USA), Banbury (UK) and Maranello (Italy).",
      "Founder Gene Haas also co-owns a championship-winning NASCAR team.",
    ],
    current: true,
  },
  cadillac: {
    constructorId: "cadillac",
    name: "Cadillac F1 Team",
    shortName: "Cadillac",
    color: "#B29A5B",
    secondaryColor: "#0A0A0A",
    base: "Fishers, United States",
    principal: "Graeme Lowdon",
    powerUnit: "Ferrari",
    firstEntry: 2026,
    championships: 0,
    funFacts: [
      "Cadillac is Formula One's 11th team and the first all-new entry since Haas in 2016.",
      "The project is backed by General Motors with a purpose-built campus in Fishers, Indiana.",
      "GM plans to introduce its own Cadillac power unit later in the decade.",
      "The team signed race winners Sergio Pérez and Valtteri Bottas for its debut season.",
    ],
    current: true,
  },

  /* ------------------------------ Historical ------------------------------ */

  lotus: {
    constructorId: "lotus",
    name: "Team Lotus",
    shortName: "Lotus",
    color: "#1B5B41",
    secondaryColor: "#F3D22B",
    base: "Hethel, United Kingdom",
    principal: "Colin Chapman",
    powerUnit: "Various (Climax, Ford, Renault)",
    firstEntry: 1958,
    championships: 7,
    funFacts: [
      "Colin Chapman's Lotus pioneered the monocoque chassis, ground effect and sponsorship liveries.",
      "Jim Clark, Graham Hill, Jochen Rindt, Emerson Fittipaldi and Mario Andretti all won titles in Lotus cars.",
      "The Lotus 79 of 1978 was the first F1 car designed around ground-effect aerodynamics.",
    ],
    current: false,
  },
  brabham: {
    constructorId: "brabham",
    name: "Brabham",
    shortName: "Brabham",
    color: "#00429B",
    secondaryColor: "#DA291C",
    base: "Chessington, United Kingdom",
    principal: "Jack Brabham / Bernie Ecclestone",
    powerUnit: "Various (Repco, Ford, BMW)",
    firstEntry: 1962,
    championships: 2,
    funFacts: [
      "Jack Brabham remains the only driver to win the world championship in a car bearing his own name (1966).",
      "The 1978 Brabham BT46B 'fan car' won its only race before being withdrawn.",
      "Nelson Piquet won two of his three titles with Brabham in 1981 and 1983.",
    ],
    current: false,
  },
  tyrrell: {
    constructorId: "tyrrell",
    name: "Tyrrell",
    shortName: "Tyrrell",
    color: "#0F2D9C",
    secondaryColor: "#FFFFFF",
    base: "Ockham, United Kingdom",
    principal: "Ken Tyrrell",
    powerUnit: "Ford Cosworth",
    firstEntry: 1970,
    championships: 1,
    funFacts: [
      "Tyrrell famously operated from a woodyard in Surrey.",
      "The 1976 Tyrrell P34 is F1's only six-wheeled race winner.",
      "Jackie Stewart won the 1971 and 1973 titles for Ken Tyrrell's team.",
    ],
    current: false,
  },
  benetton: {
    constructorId: "benetton",
    name: "Benetton",
    shortName: "Benetton",
    color: "#009B77",
    secondaryColor: "#FFEB00",
    base: "Enstone, United Kingdom",
    principal: "Flavio Briatore",
    powerUnit: "Ford / Renault",
    firstEntry: 1986,
    championships: 1,
    funFacts: [
      "Michael Schumacher won his first two world titles with Benetton in 1994 and 1995.",
      "The team grew out of Toleman, where Ayrton Senna made his F1 debut.",
      "Benetton's Enstone factory lives on today as the home of Alpine.",
    ],
    current: false,
  },
  renault: {
    constructorId: "renault",
    name: "Renault",
    shortName: "Renault",
    color: "#FFF500",
    secondaryColor: "#000000",
    base: "Enstone, United Kingdom",
    principal: "Flavio Briatore",
    powerUnit: "Renault",
    firstEntry: 1977,
    championships: 2,
    funFacts: [
      "Renault introduced turbocharging to F1 in 1977 — rivals called the car the 'yellow teapot' until it started winning.",
      "Fernando Alonso ended Ferrari's dominance with back-to-back titles in 2005 and 2006.",
      "Renault power won 12 constructors' championships across its works and customer teams.",
    ],
    current: false,
  },
  brawn: {
    constructorId: "brawn",
    name: "Brawn GP",
    shortName: "Brawn",
    color: "#B9F730",
    secondaryColor: "#FFFFFF",
    base: "Brackley, United Kingdom",
    principal: "Ross Brawn",
    powerUnit: "Mercedes",
    firstEntry: 2009,
    championships: 1,
    funFacts: [
      "Brawn GP won both world championships in its only season of existence (2009).",
      "The team was bought from Honda for £1 after the 2008 financial crisis.",
      "Its 'double diffuser' loophole gave Jenson Button six wins in the first seven races.",
    ],
    current: false,
  },
  cooper: {
    constructorId: "cooper",
    name: "Cooper",
    shortName: "Cooper",
    color: "#0B3D2E",
    secondaryColor: "#FFFFFF",
    base: "Surbiton, United Kingdom",
    principal: "Charles Cooper",
    powerUnit: "Climax",
    firstEntry: 1950,
    championships: 2,
    funFacts: [
      "Cooper's rear-engined cars revolutionized F1 — within three years every winning car copied the layout.",
      "Jack Brabham won consecutive titles for Cooper in 1959 and 1960.",
      "The company started out building single-seaters from war-surplus materials.",
    ],
    current: false,
  },
  matra: {
    constructorId: "matra-ford",
    name: "Matra",
    shortName: "Matra",
    color: "#14418F",
    secondaryColor: "#FFFFFF",
    base: "Vélizy, France",
    principal: "Ken Tyrrell (entrant)",
    powerUnit: "Ford Cosworth",
    firstEntry: 1968,
    championships: 1,
    funFacts: [
      "Matra was a French aerospace company that applied aviation engineering to racing.",
      "Jackie Stewart won the 1969 championship in a Matra MS80 run by Ken Tyrrell.",
      "Matra's V12 engine was famed as one of the best-sounding in motorsport history.",
    ],
    current: false,
  },
  bmw_sauber: {
    constructorId: "bmw_sauber",
    name: "BMW Sauber",
    shortName: "BMW Sauber",
    color: "#0066B1",
    secondaryColor: "#FFFFFF",
    base: "Hinwil, Switzerland",
    principal: "Mario Theissen",
    powerUnit: "BMW",
    firstEntry: 2006,
    championships: 0,
    funFacts: [
      "Robert Kubica took the team's only win at Canada 2008, a year after his huge accident at the same track.",
      "BMW Sauber briefly led both championships in mid-2008.",
      "The Hinwil facility now houses the Audi F1 team.",
    ],
    current: false,
  },
  jordan: {
    constructorId: "jordan",
    name: "Jordan Grand Prix",
    shortName: "Jordan",
    color: "#F9C218",
    secondaryColor: "#111111",
    base: "Silverstone, United Kingdom",
    principal: "Eddie Jordan",
    powerUnit: "Various (Hart, Peugeot, Honda)",
    firstEntry: 1991,
    championships: 0,
    funFacts: [
      "Jordan gave Michael Schumacher his F1 debut at Spa in 1991.",
      "The team's 1998 one-two at a soaked Spa was its first victory.",
      "Jordan's lineage continues today as Aston Martin.",
    ],
    current: false,
  },
};

const FALLBACK_COLOR = "#9CA3AF";

export function getTeamMeta(constructorId: string): TeamMeta | undefined {
  return TEAM_META[constructorId];
}

export function getTeamColor(constructorId: string): string {
  return TEAM_META[constructorId]?.color ?? FALLBACK_COLOR;
}

export function getCurrentTeams(): TeamMeta[] {
  return Object.values(TEAM_META).filter((team) => team.current);
}
